services:
  pricing-grid:
    build: .
    container_name: pricing-grid
    depends_on:
      - postgres
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - pricing-grid-network
    env_file:
      - .env

  postgres:
    container_name: pricing-grid-db
    image: postgres
    restart: on-failure
    networks:
      - pricing-grid-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pricingGrid:/var/lib/postgresql/data
    env_file:
      - .env

networks:
  pricing-grid-network:

volumes:
  pricingGrid: